apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharpfiles-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharpfiles
  template:
    metadata:
      labels:
        app: sharpfiles
    spec:
      hostname: sharpfiles
      containers:
      - name: sharpfiles
        image: sharp6292/sharpfiles
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: sharexpass-secret
              key: SHAREXPASS
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: domain-secret
              key: DOMAIN
        volumeMounts:
        - name: sharpfiles-data
          mountPath: /sharex/files/
      volumes:
      - name: sharpfiles-data
        persistentVolumeClaim:
          claimName: sharpfiles-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: sharpfiles-service
spec:
  selector:
    app: sharpfiles
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sharpfiles-ingress
spec:
  rules:
  - host: files.mcaq.me
    http:
      paths:
      - path: /
        backend:
          serviceName: sharpfiles-service
          servicePort: 80

  tls:
  - hosts:
    - files.mcaq.me
    secretName: ${DOMAIN}-tls