apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharpfiles-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/files"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharpfiles-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharpfiles-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharpfiles
  template:
    metadata:
      labels:
        app: sharpfiles
    spec:
      hostname: sharpfiles
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - vmi1031871.contaboserver.net
      containers:
      - name: sharpfiles
        image: sharp6292/sharpfiles
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: sharex-secret
              key: SHAREXPASS
        - name: DOMAIN
          value: files.mcaq.me
        volumeMounts:
        - name: sharpfiles-data
          mountPath: /sharex/files/
      volumes:
      - name: sharpfiles-data
        persistentVolumeClaim:
          claimName: sharpfiles-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: sharpfiles-service
spec:
  selector:
    app: sharpfiles
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharpfiles-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  tls:
  - hosts:
      - files.mcaq.me
    secretName: files-mcaq-me-tls
  rules:
  - host: files.mcaq.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sharpfiles-service
              port:
                number: 8080