#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: sharelatex/sharelatex
  # -- image tag
  tag: 2.7.1
  # -- image pull policy
  pullPolicy: IfNotPresent

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

    hosts:
      - host: "overleaf.${DOMAIN}"

    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls:
     - secretName: ${DOMAIN}-tls
       hosts:
         - "overleaf.${DOMAIN}"

persistence:
  data:
    enabled: true
    mountPath: /var/lib/sharelatex

redis:
  enabled: true

mongodb:
  enabled: true