apiVersion: v1
kind: Service
metadata:
  name: kimai-service
  namespace: default
  labels:
    app: kimai
    env: prod
spec:
  ports:
  - port: 8001
  selector:
    app: kimai
    env: prod
  clusterIP: None
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kimai-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: timesheet.${DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kimai-service
              port:
                number: 8001
tls:
  - hosts:
      - timesheet.${DOMAIN}
    secretName: ${DOMAIN_NAME}-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimai-deployment
  namespace: default
  labels:
    app: kimai
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai
      env: prod
  template:
    metadata:
      labels:
        app: kimai
        env: prod
    spec:
      containers:
      - name: kimai
        image: kimai/kimai2:fpm-2.0.14-prod
        env:
          - name: DATABASE_URL
            value: "mysql://${SQL_USER}:${SQL_PASS}@mysql.default.svc.cluster.local:3306/kimai"
          - name: TRUSTED_HOSTS
            value: "localhost,timesheet.${DOMAIN},kimai.local"
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "850m"
            memory: "1200Mi"
          limits:
            cpu: "1000m"
            memory: "1500Mi"