apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    env: prod
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    env: prod
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    env: prod
spec:
  selector:
    matchLabels:
      app: mysql
      env: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        env: prod
    spec:
      containers:
      - image: mysql:5.7.34
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${SQL_PASS}
        - name: MYSQL_USER
          value: ${SQL_USER}
        - name: MYSQL_PASSWORD
          value: ${SQL_PASS}
        - name: MYSQL_DATABASE
          value: kimai
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: "850m"
            memory: "1200Mi"
          limits:
            cpu: "1000m"
            memory: "1500Mi"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc